all:
  hosts:
    mail.example.com:
  children:
    webserver:
      hosts:
        foo.example.com:
          ansible_connection: local
    dbserver:
      hosts:
        bar.example.com:
          ansible_connection: local
